#! /usr/bin/env bash

# Install missing Rust crates, toolchain and Leptos
rustup toolchain install nightly --allow-downgrade
rustup target add wasm32-unknown-unknown
cargo install cargo-leptos --locked

# Run the build
cargo leptos build --release
